service: default
runtime: nodejs12

handlers:
  - url: /favicon\.ico
    static_files: dist/crousorama-front/favicon.ico
    upload: dist/crousorama-front/favicon\.ico

  - url: /(.*\..*$)
    static_files: dist/crousorama-front/\1
    upload: dist/crousorama-front/(.*\..*$)

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    static_files: dist/crousorama-front/index.html
    upload: dist/crousorama-front/index\.html
    http_headers:
      Strict-Transport-Security: max-age=31536000; includeSubDomains;
      Access-Control-Allow-Origin: crousorama.appspot.com
